import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "../Component/Header";
import ClientSessionProvider from "../Component/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSessionProvider>
          <main>
            <Header />
            <div className="max-w-4xl mx-auto p-6">{children}</div>
          </main>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
